# Generated by Django 4.2.7 on 2023-12-06 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_address_is_reusable_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_owner_product_not_canceled',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'canceled'), _negated=True), fields=('course', 'owner', 'product'), name='unique_owner_course_product_not_canceled', violation_error_message='An order for this product and course already exists.'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'canceled'), _negated=True), fields=('enrollment', 'owner', 'product'), name='unique_owner_enrollment_product_not_canceled', violation_error_message='An order for this product and enrollment already exists.'),
        ),
    ]
